const products = [
  { id:'attigai-classic', name:'The Attigai', category:'Temple Necklaces', price:1850, image:'https://raw.githubusercontent.com/clinceraj/ruth-jewels-1/main/ATTIGAI-01.jpeg', tag:'Signature', description:'A regal collar necklace with a rich, temple-inspired silhouette. Made to take centre stage at every celebration.', colour:'Antique gold', styling:'Best with silk sarees and high necklines.' },
  { id:'attigai-emerald', name:'Emerald Attigai', category:'Temple Necklaces', price:2100, image:'https://raw.githubusercontent.com/clinceraj/ruth-jewels-1/main/ATTIGAI-04.png', tag:'New arrival', description:'Our classic Attigai, brightened by emerald-green detailing for a considered burst of colour.', colour:'Gold & emerald', styling:'Style with jewel tones for a polished look.' },
  { id:'attigai-sun', name:'Sunlit Attigai', category:'Temple Necklaces', price:1750, image:'https://raw.githubusercontent.com/clinceraj/ruth-jewels-1/main/ATTIGAI-05.png', tag:'Bestseller', description:'A luminous temple necklace designed with graceful details and a wonderfully easy-to-wear presence.', colour:'Warm gold', styling:'An effortless choice for daytime ceremonies.' },
  { id:'lotus-choker', name:'Lotus Line Choker', category:'Chokers', price:1450, image:'https://raw.githubusercontent.com/clinceraj/ruth-jewels-1/main/ONE%20LINE%20LOTUS%20CHOCKER-06.png', tag:'Ruth edit', description:'A finely detailed choker that frames the neckline with a row of lotus-inspired motifs.', colour:'Classic gold', styling:'Layer with a fine chain or let it shine alone.' },
  { id:'lakshmi-choker', name:'Lakshmi Choker', category:'Chokers', price:1650, image:'https://raw.githubusercontent.com/clinceraj/ruth-jewels-1/main/LAKSHMI%20CHOKER-01.png', tag:'Iconic', description:'A sculptural Lakshmi choker with ceremonial character and heirloom-worthy detail.', colour:'Antique gold', styling:'Made for memorable entrances.' },
  { id:'coin-necklace', name:'Coin Necklace', category:'Bridal Edit', price:1250, image:'https://raw.githubusercontent.com/clinceraj/ruth-jewels-1/main/COIN%20NECKLACE-01.jpeg', tag:'Everyday heirloom', description:'A classic coin necklace that lends a heritage feel to both celebration and everyday dressing.', colour:'Soft gold', styling:'Beautiful alone or layered with a longer chain.' },
  { id:'floral-ad', name:'Floral AD Necklace', category:'Bridal Edit', price:2350, image:'https://raw.githubusercontent.com/clinceraj/ruth-jewels-1/main/FLORAL%20AD%20NECKLACE-01.png', tag:'Bridal favourite', description:'A luminous floral statement necklace for wedding rituals, receptions, and the photographs that follow.', colour:'Gold & crystal', styling:'Pair with a clean silk blouse and matching earrings.' },
  { id:'mango-mala', name:'Mango Mala', category:'Temple Necklaces', price:2500, image:'https://raw.githubusercontent.com/clinceraj/ruth-jewels-1/main/MANGO%20MALA%20WITH%20LEKSHMI%20PENDANT-01.png', tag:'Limited edit', description:'A grand mango mala with a Lakshmi pendantâ€”created for the most special chapters.', colour:'Gold & ruby', styling:'A statement for bridal and festive dressing.' },
  { id:'palakk-haram', name:'Palakk Haram', category:'Bridal Edit', price:2200, image:'https://raw.githubusercontent.com/clinceraj/ruth-jewels-1/main/PALAKK%20HARAM-01.png', tag:'Ceremonial', description:'A traditional silhouette reimagined in a striking, modern proportion.', colour:'Gold & green', styling:'A natural match for classic bridal colour palettes.' },
  { id:'gold-green', name:'Gold & Green', category:'Temple Necklaces', price:950, image:'https://raw.githubusercontent.com/clinceraj/ruth-jewels-1/main/GOLD%20AND%20GREEN-01.png', tag:'Easy elegance', description:'A refined gold and green necklace for a little ritual in the everyday.', colour:'Gold & green', styling:'Try it with a simple kurta or an evening saree.' }
];

const money = value => `SAR ${new Intl.NumberFormat('en-SA').format(value)}`;
const getCart = () => JSON.parse(localStorage.getItem('ruth-jewels-cart') || '[]');
const saveCart = cart => { localStorage.setItem('ruth-jewels-cart', JSON.stringify(cart)); updateCartCount(); };
const findProduct = id => products.find(product => product.id === id);
const page = location.pathname.split('/').pop() || 'index.html';

function headerTemplate() {
  const active = name => page === name ? 'is-current' : '';
  return `<a class="brand" href="index.html" aria-label="Ruth Jewels home">Ruth<small>Jewels</small></a><nav class="nav" aria-label="Main navigation"><a class="${active('collections.html')}" href="collections.html">Collections</a><a class="${active('about.html')}" href="about.html">Our story</a><a href="collections.html?category=Bridal+Edit">Bridal edit</a></nav><div class="header-actions"><a href="account.html">Account</a><a class="bag-link ${active('cart.html')}" href="cart.html">Bag <span class="bag-count" data-cart-count>0</span></a></div>`;
}
function footerTemplate() {
  return `<div class="footer-top"><div class="footer-brand"><a class="brand" href="index.html">Ruth<small>Jewels</small></a><p>Temple-inspired jewellery for every story, celebration, and new beginning.</p></div><div><p class="footer-heading">Explore</p><nav class="footer-links"><a href="collections.html">All collections</a><a href="collections.html?category=Temple+Necklaces">Temple necklaces</a><a href="collections.html?category=Chokers">Chokers</a><a href="collections.html?category=Bridal+Edit">Bridal edit</a></nav></div><div><p class="footer-heading">Ruth Jewels</p><nav class="footer-links"><a href="about.html">Our story</a><a href="account.html">My account</a><a href="https://www.instagram.com/ruth_jewels_/?hl=en" target="_blank" rel="noopener">Instagram</a></nav></div></div><div class="footer-bottom"><span>Â© 2026 Ruth Jewels</span><span>Curated with love and heritage</span></div>`;
}
function productCard(product) {
  return `<article class="product-card"><a class="product-image" href="product.html?id=${product.id}"><img src="${product.image}" alt="${product.name}"><span class="product-tag">${product.tag}</span></a><div class="product-info"><h3><a href="product.html?id=${product.id}">${product.name}</a></h3><span class="product-price">${money(product.price)}</span><p>${product.category}</p><button class="quick-add" type="button" data-quick-add="${product.id}">Add to bag +</button></div></article>`;
}
function updateCartCount() { document.querySelectorAll('[data-cart-count]').forEach(node => node.textContent = getCart().reduce((total,item) => total + item.quantity, 0)); }
function showToast(message) { let toast = document.querySelector('.toast'); if (!toast) { toast = document.createElement('div'); toast.className = 'toast'; document.body.append(toast); } toast.textContent = message; toast.classList.add('is-visible'); window.setTimeout(() => toast.classList.remove('is-visible'), 2600); }
function addToCart(productId) { const cart = getCart(); const existing = cart.find(item => item.id === productId); if (existing) existing.quantity += 1; else cart.push({id:productId,quantity:1}); saveCart(cart); showToast('Added to your bag.'); }
function cartTotal() { return getCart().reduce((total,item) => total + (findProduct(item.id)?.price || 0) * item.quantity, 0); }
function cartItemsTemplate(compact=false) { const cart = getCart(); if (!cart.length) return compact ? '<p>Your bag is waiting for something beautiful.</p>' : '<div class="empty-state"><h2>Your bag is waiting.</h2><p>Find a piece you will reach for time after time.</p><a class="button button--gold" href="collections.html">Explore collections</a></div>';
  return cart.map(item => { const product = findProduct(item.id); if (!product) return ''; return compact ? `<div class="summary-item"><img src="${product.image}" alt=""><div><strong>${product.name}</strong><span>${item.quantity} Ã— ${money(product.price)}</span></div></div>` : `<article class="cart-line"><img src="${product.image}" alt="${product.name}"><div><h2>${product.name}</h2><p>${product.category}</p><div class="quantity" aria-label="Quantity"><button data-adjust-quantity="${product.id}" data-change="-1" aria-label="Decrease quantity">âˆ’</button><span>${item.quantity}</span><button data-adjust-quantity="${product.id}" data-change="1" aria-label="Increase quantity">+</button></div><br><button class="remove" data-remove-item="${product.id}">Remove</button></div><span class="line-price">${money(product.price * item.quantity)}</span></article>`; }).join('');
}
function summaryTemplate(withButton=false) { const total = cartTotal(); return `<h2>Order summary</h2><div class="summary-row"><span>Subtotal</span><span>${money(total)}</span></div><div class="summary-row"><span>Delivery</span><span>Calculated at checkout</span></div><div class="summary-total"><span>Total</span><span>${money(total)}</span></div>${withButton ? '<a class="button button--gold" href="checkout.html">Continue to checkout</a>' : ''}`; }
function renderHome() { const target = document.querySelector('[data-featured-products]'); if (target) target.innerHTML = products.slice(0,3).map(productCard).join(''); }
function renderCollections() { const target = document.querySelector('[data-collection-products]'); const filters = document.querySelector('[data-category-filters]'); if (!target || !filters) return; const categories = ['All', ...new Set(products.map(product => product.category))]; let current = new URLSearchParams(location.search).get('category') || 'All'; let latestFirst = false;
  filters.innerHTML = categories.map(category => `<button class="filter-button ${category === current ? 'is-active':''}" data-filter="${category}">${category}</button>`).join('');
  const render = () => { let result = current === 'All' ? [...products] : products.filter(product => product.category === current); if (latestFirst) result.reverse(); target.innerHTML = result.map(productCard).join(''); document.querySelector('[data-product-count]').textContent = `${result.length} ${result.length === 1 ? 'piece' : 'pieces'}`; };
  filters.addEventListener('click', event => { const button = event.target.closest('[data-filter]'); if (!button) return; current = button.dataset.filter; filters.querySelectorAll('[data-filter]').forEach(item => item.classList.toggle('is-active', item === button)); render(); });
  document.querySelector('[data-sort-products]')?.addEventListener('click', event => { latestFirst = !latestFirst; event.currentTarget.innerHTML = `Sort: ${latestFirst ? 'Newest' : 'Featured'} <span>â†“</span>`; render(); }); render();
}
function renderProduct() { const root = document.querySelector('[data-product-page]'); if (!root) return; const product = findProduct(new URLSearchParams(location.search).get('id')) || products[0]; document.title = `${product.name} | Ruth Jewels`; root.innerHTML = `<p class="breadcrumbs"><a href="collections.html">Collections</a> / <a href="collections.html?category=${encodeURIComponent(product.category)}">${product.category}</a> / ${product.name}</p><section class="product-detail"><div class="product-detail-image"><img src="${product.image}" alt="${product.name}"></div><div class="product-detail-copy"><p class="eyebrow">${product.category}</p><h1>${product.name}</h1><p class="product-detail-price">${money(product.price)}</p><p class="product-detail-description">${product.description}</p><div class="product-meta"><div><span>Finish</span><strong>${product.colour}</strong></div><div><span>Styling note</span><strong>${product.styling}</strong></div><div><span>Packaging</span><strong>Gift wrapped</strong></div></div><span class="variant-label">Choose finish</span><div class="variant-options"><button class="variant-option is-selected" type="button">Gold</button><button class="variant-option" type="button">Antique</button></div><button class="button button--gold add-to-cart" type="button" data-add-to-cart="${product.id}">Add to bag â€” ${money(product.price)}</button></div></section>`;
  root.querySelectorAll('.variant-option').forEach(button => button.addEventListener('click', () => root.querySelectorAll('.variant-option').forEach(item => item.classList.toggle('is-selected', item === button))));
}
function renderCart() { const root = document.querySelector('[data-cart-page]'); if (!root) return; if (!getCart().length) { root.innerHTML = cartItemsTemplate(); return; } root.innerHTML = `<div class="cart-layout"><section>${cartItemsTemplate()}</section><aside class="cart-summary">${summaryTemplate(true)}</aside></div>`; }
function renderCheckout() { const summary = document.querySelector('[data-checkout-summary]'); if (summary) summary.innerHTML = `${cartItemsTemplate(true)}${getCart().length ? summaryTemplate() : '<p><a class="text-link" href="collections.html">Choose a piece first â†’</a></p>'}`; }
function bindInteractions() { document.addEventListener('click', event => { const quickAdd = event.target.closest('[data-quick-add],[data-add-to-cart]'); if (quickAdd) { addToCart(quickAdd.dataset.quickAdd || quickAdd.dataset.addToCart); return; } const adjust = event.target.closest('[data-adjust-quantity]'); if (adjust) { const cart = getCart(); const item = cart.find(line => line.id === adjust.dataset.adjustQuantity); if (!item) return; item.quantity += Number(adjust.dataset.change); saveCart(cart.filter(line => line.quantity > 0)); renderCart(); return; } const remove = event.target.closest('[data-remove-item]'); if (remove) { saveCart(getCart().filter(item => item.id !== remove.dataset.removeItem)); renderCart(); showToast('Removed from your bag.'); return; } const create = event.target.closest('[data-create-account]'); if (create) { event.preventDefault(); showToast('Account creation will be enabled with your secure backend.'); } });
  document.querySelector('[data-checkout-form]')?.addEventListener('submit', event => { event.preventDefault(); if (!getCart().length) { showToast('Your bag is empty.'); return; } localStorage.removeItem('ruth-jewels-cart'); updateCartCount(); event.currentTarget.innerHTML = '<h2>Thank you.</h2><p>Your demonstration order is confirmed. Connect a payment provider and order system before accepting live purchases.</p><a class="button button--gold" href="collections.html">Continue shopping</a>'; document.querySelector('[data-checkout-summary]').innerHTML = '<h2>Order received</h2><p>Your bag is now empty.</p>'; });
  document.querySelector('[data-account-form]')?.addEventListener('submit', event => { event.preventDefault(); showToast('This is a demonstration sign-in.'); });
}
function init() { document.querySelectorAll('[data-header]').forEach(node => node.innerHTML = headerTemplate()); document.querySelectorAll('[data-footer]').forEach(node => node.innerHTML = footerTemplate()); updateCartCount(); renderHome(); renderCollections(); renderProduct(); renderCart(); renderCheckout(); bindInteractions(); }
init();

